# {name} - Bukkit Plugin configuration file
# Copyright © {copyright.years} Visual Illusions Entertainment
name: {name}
main: {bukkit.main.class}
version: {plugin.version}
author: Visual Illusions Entertainment
website: {wiki}

# Visual Illusions Specific Stuff
developers: {devs}
build.number: {build}
build.time: {build.time}
program.status: {program.status}
version.check.url: {version.check.url}
issues.url: {issues}
copyright.years: {copyright.years}
# # #

commands:
  tip:
    description: Main Tips Command
    usage: /tip <add|remove|getall|reload|server> [index|message] - Tips commands
    permission: tipme.admin
  tip add:
    description: Adds a tip to the list
    usage: /tip add <tip>
    permission: tipme.admin
  tip remove:
    description: Removes a tip from the list
    usage: /tip remove <index>
    permission: tipme.admin
  tip getall:
    description: Displays all Tips by index
    usage: /tip getall
    permission: tipme.admin
  tip reload:
    description: Reloads tips from the datasource
    usage: /tip reload
    permission: tipme.admin
  tip server:
    description: Sends a tip to all players online
    usage: /tip tipserver
    permission: tipme.admin
  tipme:
    description: TipMe Information command
    usage: /tipme
    
permissions:
  tipme.admin:
    description: Gives access to all TipMe commands
    default: op
